### ISSUE TITLE
Return value must be of type string

### ISSUE THREAD

**Issue by Rohaty** [yireo/Yireo_CspWhitelistInlineJs#2]
Hi,

I'm trying this extension on Magento 2.4.7-p2, php 8.2.22.

I have set Custom whitelisting and logging No.

During checkout page it shows me an error 

Return value must be of type string, null returned at /magento/vendor/yireo/magento2-csp-whitelist-inline-js/Plugin/AddCspInlineScripts.php:34

Where could be the problem?

Regards

**Comment by Rohaty** [comment]
Problem solved, I found that I didn't delete all the old files before compiling.

Regards

**Comment by jissereitsma** [comment]
I still think that this error should not have happened in the first place, so I've added a new release 0.1.1 to fix it.
